name: OpenWar-Levels
version: '${project.version}'
main: com.openwar.openwarlevels.Main
depend:
  - OpenWar-Core
commands:
  level:
    description: Level commands
    usage: /lvl | /level
    aliases:
      - lvl
  unlock:
    description: unlock command
    usage: /unlock | /ul
    aliases:
      - ul